### ISSUE TITLE
US3 add new user data

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/capstone-project#4]
## Value Proposition

**As a** user
**I want to** create new cards 
**so that** I can be in the pool of the aviable players
​

## Description

![image](https://user-images.githubusercontent.com/116001970/207079240-0e47bd14-8cd1-4529-b409-4e056e0eaa9a.png)

​

## Acceptance Criteria

- [ ] a form to add new players in the array of players
- [ ] a save button to submit the form
- [ ] a back button to abort the form and go back to the homepage
- [ ] checkboxes for the language
- [ ] dropdown menus for skill and gender
- [ ] the header shows MatchBall New players
- [ ] a  profile picture symbol is shown if no profile picture is aviable
- [ ] a button to add a profile picture
- [ ] the new profile picture is shown after the press of the add profile picture button
- [ ] all inputs are requested, only the profile picture is not
- [ ] the submit of the form add new data in the array of all the players
      ​

## Tasks

- [ ] create a form
- [ ] create the necessary inputs
- [ ] create the two buttons
- [ ] find a way to upload a profile picture from the gallery
      ​

**Comment by ufelgen** [comment]
Hey Walter, in deiner Value Proposition ist das Wort glaube ich "available". Bei Tasks schreibst du "find a way to...", das würde ich entweder weglassen ("upload the profile picture from the gallery") oder spezifizieren ("use cloudinary to store image uploaded image files" oder so). Vom Umfang her ist es glaube ich prima :)
