### ISSUE TITLE
US4 add profile pictures in the cards

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/capstone-project#5]
## Value Proposition

**As a** user 
**I want to** see the profile pictures and the name in the matched cards  
**so that** I can recognize my friends if many people have the same name
​

## Description

![image](https://user-images.githubusercontent.com/116001970/207087615-977ac981-676d-454b-b763-cfd8d177d336.png)

​

## Acceptance Criteria

- [ ] profile pictures are shown in the homepage
- [ ] if no profile picture is available, a profile picture symbol is shown
- [ ] a navigation bar can be used to switch between homepage and add new player page
- [ ] the layout is mobile friendly
- [ ] the cards change only after the click of the search button
- [ ] more information about the use of the app

## Tasks

- [ ] add a few dummy pictures in the array of all the players
- [ ] display the profile pictures in the cards
- [ ] make the buttons and cards big enough for mobile users
- [ ] code a navigation bar and switch to the form page if the plus button is clicked
      ​

## Complexity

...

**Comment by WalterRestifo** [comment]
Du hast Recht Ulli, ich habe die NavBar jetzt in eine neue US ausgelagert, da es nicht wirklich mit dem Rendern der Profilbilder zu tun hat. Danke!
