### ISSUE TITLE
US 5 NavBar

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/capstone-project#6]
## Value Proposition

**As a** user
**I want to** have a navigation bar 
**so that** I can switch between pages
​

## Description

![image](https://user-images.githubusercontent.com/116001970/207087615-977ac981-676d-454b-b763-cfd8d177d336.png)
​

## Acceptance Criteria

- [ ] the navigation bar works
- [ ] the symbols of the navigation bar cannot be misunderstood
      ​

## Tasks

- [ ] create a navigation bar with 2 buttons for switching between the homepage and the add new player page
      ​

**Comment by Elgin-Schultz** [comment]
Maybe you could specify the symbols as house and plus sign in the acceptance criteria as addition to the sketch... no must!
